apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tharaka-2440"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tharaka-2440"
  template:
    metadata:
      labels:
        app: "tharaka-2440"
    spec:
      containers:
        - name: "tharaka-2440"
          image: "djtharaka.azurecr.io/tharaka"
          ports:
          - containerPort: 80