apiVersion: v1
kind: Service
metadata:
    name: "lkdfd-4ffe"
    labels:
        app: "lkdfd-4ffe"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "lkdfd-4ffe"