on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n hasiya -g hasiyaa218-rg --location "UK South" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n hasiya --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n hasiya --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n hasiya --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: hasiya.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t hasiya.azurecr.io/lkdfd:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push hasiya.azurecr.io/lkdfd:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_lkdfd_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep lkdfdb708 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace lkdfdb708`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: lkdfdb708
        container-registry-url: hasiya.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: lkdfddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: lkdfdb708
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          hasiya.azurecr.io/lkdfd:${{ github.sha }}
        imagepullsecrets: |
          lkdfddockerauth   
